### PR TITLE
bugfix: Stricter check for "tests" and "docs" directories in sp-repo-review 

### PR DESCRIPTION
**Pull request by ukmo-ccbunney**
### Summary
The `sp-repo-review` checks for the existence of the `tests` (PY005) and `docs` (PY004) directories are too lenient and often return false positives.

### Details
The existence of a file or directory in the repo that _contains_ the word "docs" or "tests" will result in a pass for these tests.

For example, the existence of the `.readthedocs` file causes the `PY004 Has docs folder` test to pass, simply because it contains the work `docs`. Similarly, an innocuously named file such as `fastest.txt` would result in a false pass of `PY005 Has tests folder`.

This PR modifies the `PY004` and `PY005` checks to:
- Compare against string `tests` or `docs`, rather than testing if the filename contains that string.
- Require that the path is a directory
- `test` is no longer a match for PY005: should be `tests` as per [Scientific Python: package-structure](https://learn.scientific-python.org/development/guides/packaging-simple/#package-structure);  this required an update to the internal tests.

### CODE REVIEW

**Comment by henryiii** [comment]
Making this require a folder is great, and I think that solves your initial issue. I'm a little worried about too many false negatives; old packages that use `/test` or packages that use `tests-integration`, for example, do have tests, so this check probably should pass.

**Comment by ukmo-ccbunney** [comment]
> Making this require a folder is great, and I think that solves your initial issue. I'm a little worried about too many false negatives; old packages that use `/test` or packages that use `tests-integration`, for example, do have tests, so this check probably should pass.

Hi @henryiii 
OK - that makes sense, although I made this change taking into account the very specific guidance in the "packaging" section of the [Scientific Python guide](https://learn.scientific-python.org/development/guides/packaging-simple/#package-structure):

> You should have a /tests folder PY005 (recommended) and/or a src/<package>/tests folder.

How do you feel about a slightly more lenient check for a **folder** that **starts with** the word `test`?

**Comment by henryiii** [comment]
I think that's fine.

**Comment by ukmo-ccbunney** [comment]
> I think that's fine.

Great - I've pushed up a new commit that does this.
It also adds some extra unit tests for the PY004 (has docs) and PY005 (has tests) checks.

**Comment by henryiii** [comment]
Thanks!

**Pull request merged**
